/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRINCIPAL;

import CodigoPOJO.CodigoPOJO;
import JDBC.Conexion;
import JDBC.PersonaJDBC;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author agonzalez
 */
public class Principal extends javax.swing.JFrame {

    Statement st;
    PreparedStatement ps = null;
    ResultSet rs;

    /**
     * Creates new form Principal
     */
    //TextAutoCompleter textAutoCompleter;
    public Principal() {
        initComponents();
        TextPrompt proveedor = new TextPrompt("Codigo Proveedor", txtproveedor);
        TextPrompt codigobarras = new TextPrompt("Codigo de barras", txtcodigobarras);
        TextPrompt descripcion = new TextPrompt("Descripcion", txtdescripcion);
        llenargeneros();
        llenargrupos();
        AutoCompleteDecorator.decorate(jcgenero);
        AutoCompleteDecorator.decorate(jcgrupo);
        /*  textAutoCompleter = new TextAutoCompleter(txtgenero, new AutoCompleterCallback() {
         @Override
         public void callback(Object o) {
                Object a = textAutoCompleter.findItem(o);
                CodigoPOJO personaPOJO = (CodigoPOJO) a;
            }
        });
        PersonaJDBC.cargargeneros(textAutoCompleter);
        textAutoCompleter = new TextAutoCompleter(txtgrupos, new AutoCompleterCallback() {
            @Override
            public void callback(Object o) {
                Object a = textAutoCompleter.findItem(o);
                CodigoPOJO personaPOJO = (CodigoPOJO) a;
            }
        });

        PersonaJDBC.cargargrupos(textAutoCompleter);*/
    }

    public void llenargeneros() {
        jcgenero.removeAllItems();

        try {
            Conexion con = new Conexion();
            Connection conn = con.getConnection();
            st = conn.createStatement();

            rs = st.executeQuery("select * from generos order by descripcion asc");

            while (rs.next()) {
                String elemento = rs.getString("descripcion").trim();
                jcgenero.addItem(elemento);
            }
            st.close();
        } catch (Exception e) {
            System.out.println("ERROR: failed to load HSQLDB JDBC driver.");
            e.printStackTrace();
            return;
        }
    }

    public void llenargrupos() {
        jcgrupo.removeAllItems();

        try {
            Conexion con = new Conexion();
            Connection conn = con.getConnection();
            st = conn.createStatement();

            rs = st.executeQuery("select * from grupos order by descripcion asc");

            while (rs.next()) {
                String elemento = rs.getString("descripcion").trim();
                jcgrupo.addItem(elemento);
            }
            st.close();
        } catch (Exception e) {
            System.out.println("ERROR: failed to load HSQLDB JDBC driver.");
            e.printStackTrace();
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtproveedor = new javax.swing.JTextField();
        txtcodigobarras = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jcgrupo = new javax.swing.JComboBox();
        jcgenero = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lblcodigobarras = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblproveedor = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText(" ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        txtproveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtproveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproveedorFocusGained(evt);
            }
        });
        txtproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtproveedorKeyTyped(evt);
            }
        });
        getContentPane().add(txtproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 30));

        txtcodigobarras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigobarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigobarrasKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodigobarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 30));

        txtdescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyTyped(evt);
            }
        });
        getContentPane().add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 140, 30));

        jcgrupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcgrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, 30));

        jcgenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 30));

        jLabel1.setText("Grupo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 65, -1, -1));

        lblcodigobarras.setText("  ");
        getContentPane().add(lblcodigobarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 6, 130, -1));

        jLabel4.setText("Genero");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        lblproveedor.setText(" ");
        getContentPane().add(lblproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 140, -1));

        lbldescripcion.setText("  ");
        getContentPane().add(lbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 6, 130, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtproveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproveedorFocusGained

      
    }//GEN-LAST:event_txtproveedorFocusGained

    private void txtproveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproveedorKeyTyped
        if (txtproveedor.getText().length() > 0) {
            lblproveedor.setText("Proveedor");
        } else {
            lblproveedor.setText("");
        }
    }//GEN-LAST:event_txtproveedorKeyTyped

    private void txtcodigobarrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigobarrasKeyTyped
        if (txtcodigobarras.getText().length() > 0) {
            lblcodigobarras.setText("Codigo de barras");
        } else {
            lblcodigobarras.setText("");
        }
    }//GEN-LAST:event_txtcodigobarrasKeyTyped

    private void txtdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyTyped
           if (txtdescripcion.getText().length()>0) {
    lbldescripcion.setText("Descripcion");
         }   else{
 lbldescripcion.setText("");
}
    }//GEN-LAST:event_txtdescripcionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jcgenero;
    private javax.swing.JComboBox jcgrupo;
    private javax.swing.JLabel lblcodigobarras;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblproveedor;
    private javax.swing.JTextField txtcodigobarras;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtproveedor;
    // End of variables declaration//GEN-END:variables
}
